// Package trigon is a typed client for the Trigon API.
//
// Generated by scripts/generate_sdk.py from spec/openapi.json.
// Do not edit: regenerate instead, or tests/test_sdk.py fails.
package trigon

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// ContractVersion is the version of spec/openapi.json this client was generated from.
const ContractVersion = "0.1.0"

// Usage is part of the contract.
type Usage struct {
	// Schema tokens served from a cross-request KV prefix cache rather than
	// recomputed. 0 means this request recomputed its schema block -- either
	// the cache is off, or this was the first request carrying this schema.
	// Read a 0 as 'not cached on this request', never as 'not cacheable': the
	// layout makes the schema prefix cacheable and tests/test_independence.py
	// asserts it.
	CachedSchemaTokens int `json:"cached_schema_tokens,omitempty"`
	// Total tokens prefilled. There is no decode half, so this is the whole
	// cost.
	PrefillTokens int `json:"prefill_tokens,omitempty"`
	// Readout slots, one or more per question.
	ReadoutTokens int `json:"readout_tokens,omitempty"`
	// Tokens the question schemas compiled to, across all questions.
	SchemaTokens int `json:"schema_tokens,omitempty"`
	// Tokens the state compiled to.
	StateTokens int `json:"state_tokens,omitempty"`
}

// Timing is part of the contract.
type Timing struct {
	// Compiling the schema layout and its attention mask.
	CompileMs float64 `json:"compile_ms,omitempty"`
	// The single forward pass. There is no decode.
	ModelMs float64 `json:"model_ms,omitempty"`
	// Wall clock for the whole request.
	TotalMs float64 `json:"total_ms,omitempty"`
}

// EvidenceSpan: One span of the state that drove an answer.
type EvidenceSpan struct {
	// One past the last character, so `state[start:end]` is the span.
	End int `json:"end"`
	// How strongly this span drove the answer. Under `span_head` it is the
	// head's probability that the span is part of a human rationale, fitted
	// with a proper scoring rule and never calibrated or gated; under
	// `gradient_x_input` and `integrated_gradients` it is relative within this
	// answer, 1 being its strongest token, and is not a probability at all.
	Score float64 `json:"score"`
	// First character of the span in the state string.
	Start int `json:"start"`
	// `state[start:end]`, so a caller need not slice it.
	Text string `json:"text"`
}

// ChoiceAnswer: A distribution over exactly the options the request
// declared.
type ChoiceAnswer struct {
	// How concentrated the distribution is, scaled by log(option count) so a
	// 2-option and a 77-option answer read comparably: 0 is uniform, 1 is
	// certain. Derived from the calibrated distribution, and always from the
	// full one.
	Confidence float64 `json:"confidence"`
	// The coverage that prediction set guarantees.
	CoverageTarget *float64 `json:"coverage_target,omitempty"`
	// Present when `include_evidence` was asked for: the spans of the state
	// that drove this answer, in order of position. Empty means nothing
	// cleared the threshold, which is an answer, not an error.
	Evidence []EvidenceSpan `json:"evidence,omitempty"`
	// How `evidence` was produced. `span_head`: a head trained on human
	// rationales. `gradient_x_input`: attribution of the selected label to
	// each state token, from a model never shown a rationale -- a statement
	// about the model, not a prediction of what a person would highlight.
	// `integrated_gradients`: the same kind of attribution, integrated along a
	// path from an empty state to this one. `lexical_overlap`: the lexical
	// floor's word matches. `unavailable`: this backend cannot attribute, and
	// `evidence` is empty for that reason rather than because nothing
	// mattered.
	EvidenceMethod *string `json:"evidence_method,omitempty"`
	// Present when a conformal profile was applied: the options that survive
	// at the profile's coverage target. A singleton set is the useful case; an
	// empty one means abstain, not that no answer exists.
	PredictionSet []string `json:"prediction_set,omitempty"`
	// Calibrated probability per option, in declared order. Sums to 1 unless
	// `truncated`.
	Probabilities map[string]float64 `json:"probabilities"`
	// How much of the distribution survived trimming.
	ProbabilityMass *float64 `json:"probability_mass,omitempty"`
	// The pre-calibration distribution, if you asked for it.
	RawProbabilities map[string]float64 `json:"raw_probabilities,omitempty"`
	// The most probable option. Always one you declared.
	Selected string `json:"selected"`
	// Present when the large-cardinality stage narrowed the option set: how
	// many options you declared. Options the prefilter dropped come back at
	// probability 0 rather than being omitted -- you declared them, so the
	// answer mentions them.
	ShortlistedFrom *int `json:"shortlisted_from,omitempty"`
	// True when `top_probabilities` trimmed the distribution. The
	// probabilities returned are then the real ones, NOT renormalised, so they
	// sum to less than 1; `probability_mass` says how much they cover.
	// `selected` and `confidence` are computed over the full distribution
	// either way.
	Truncated bool   `json:"truncated,omitempty"`
	Type      string `json:"type,omitempty"`
}

// ScoreAnswer: A distribution over the declared levels, plus its
// expectation.
type ScoreAnswer struct {
	// Concentration of an ORDERED distribution, from its dispersion rather
	// than its entropy -- mass on two adjacent levels is more confident than
	// the same mass split across the ends, and entropy cannot see the
	// difference.
	Confidence float64 `json:"confidence"`
	// The coverage that prediction set guarantees.
	CoverageTarget *float64 `json:"coverage_target,omitempty"`
	// Present when `include_evidence` was asked for: the spans of the state
	// that drove this answer, in order of position. Empty means nothing
	// cleared the threshold, which is an answer, not an error.
	Evidence []EvidenceSpan `json:"evidence,omitempty"`
	// How `evidence` was produced. `span_head`: a head trained on human
	// rationales. `gradient_x_input`: attribution of the selected label to
	// each state token, from a model never shown a rationale -- a statement
	// about the model, not a prediction of what a person would highlight.
	// `integrated_gradients`: the same kind of attribution, integrated along a
	// path from an empty state to this one. `lexical_overlap`: the lexical
	// floor's word matches. `unavailable`: this backend cannot attribute, and
	// `evidence` is empty for that reason rather than because nothing
	// mattered.
	EvidenceMethod *string `json:"evidence_method,omitempty"`
	// Levels surviving the conformal profile, if one was applied.
	PredictionSet []string `json:"prediction_set,omitempty"`
	// Calibrated probability per level.
	Probabilities map[string]float64 `json:"probabilities"`
	// How much of the distribution survived trimming.
	ProbabilityMass *float64 `json:"probability_mass,omitempty"`
	// The pre-calibration distribution, if you asked for it.
	RawProbabilities map[string]float64 `json:"raw_probabilities,omitempty"`
	// The expectation of the distribution below, on your level values (or
	// level indices when you declared none). Not a regression output: it
	// cannot land outside the scale you declared.
	Score float64 `json:"score"`
	// See ChoiceAnswer. `score` and `confidence` are always computed over the
	// full distribution, never over what survived truncation.
	Truncated bool   `json:"truncated,omitempty"`
	Type      string `json:"type,omitempty"`
}

// NoulAnswer: No confidence field, by design: for a binary question the
// probability already carries everything a confidence statistic could
// summarise.
type NoulAnswer struct {
	// Present when `include_evidence` was asked for: the spans of the state
	// that drove this answer, in order of position. Empty means nothing
	// cleared the threshold, which is an answer, not an error.
	Evidence []EvidenceSpan `json:"evidence,omitempty"`
	// How `evidence` was produced. `span_head`: a head trained on human
	// rationales. `gradient_x_input`: attribution of the selected label to
	// each state token, from a model never shown a rationale -- a statement
	// about the model, not a prediction of what a person would highlight.
	// `integrated_gradients`: the same kind of attribution, integrated along a
	// path from an empty state to this one. `lexical_overlap`: the lexical
	// floor's word matches. `unavailable`: this backend cannot attribute, and
	// `evidence` is empty for that reason rather than because nothing
	// mattered.
	EvidenceMethod *string `json:"evidence_method,omitempty"`
	// Calibrated probability that the judgement holds. There is no confidence
	// field by design: for a binary question the probability already carries
	// everything a confidence statistic could summarise, and 0.5 is the model
	// saying it does not know.
	Probability float64 `json:"probability"`
	// The pre-calibration probability, if you asked for it.
	RawProbability *float64 `json:"raw_probability,omitempty"`
	Type           string   `json:"type,omitempty"`
}

// Answer is one question's answer, discriminated on Type exactly as the
// contract declares it. Exactly one of Choice, Score and Noul is set.
type Answer struct {
	Type   string
	Choice *ChoiceAnswer
	Score  *ScoreAnswer
	Noul   *NoulAnswer
}

// UnmarshalJSON reads the discriminator and decodes into the matching answer.
func (a *Answer) UnmarshalJSON(data []byte) error {
	var head struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &head); err != nil {
		return err
	}
	a.Type = head.Type
	switch head.Type {
	case "choice":
		a.Choice = new(ChoiceAnswer)
		return json.Unmarshal(data, a.Choice)
	case "score":
		a.Score = new(ScoreAnswer)
		return json.Unmarshal(data, a.Score)
	case "noul":
		a.Noul = new(NoulAnswer)
		return json.Unmarshal(data, a.Noul)
	}
	return fmt.Errorf("trigon: unknown answer type %q", head.Type)
}

// Response is the answer to one Decide call.
type Response struct {
	ID string `json:"id"`
	// Model is the concrete build that answered. Never an alias.
	Model   string            `json:"model"`
	Answers map[string]Answer `json:"answers"`
	Usage   Usage             `json:"usage"`
	Timing  Timing            `json:"timing"`
	Tier    string            `json:"tier"`
}

// Question is a typed question. The request side stays a plain map: the
// gateway validates it and returns a 422 naming the offending field, which
// is a better error than one this client could invent.
type Question map[string]any

// Choice asks for one of the named options. An option is a name, or a map
// such as {"name": ..., "criteria": ...}.
func Choice(instructions string, options ...any) Question {
	return Question{"type": "choice", "instructions": instructions, "options": named(options)}
}

// Score asks for a position on the ordered levels.
func Score(instructions string, levels ...any) Question {
	return Question{"type": "score", "instructions": instructions, "levels": named(levels)}
}

// Noul asks a yes/no judgement. No confidence field, by design.
func Noul(instructions string) Question {
	return Question{"type": "noul", "instructions": instructions}
}

func named(items []any) []any {
	out := make([]any, len(items))
	for i, item := range items {
		if s, ok := item.(string); ok {
			out[i] = map[string]any{"name": s}
		} else {
			out[i] = item
		}
	}
	return out
}

// Error is a non-2xx response. Status and Payload carry the detail.
type Error struct {
	Status  int
	Payload any
}

func (e *Error) Error() string {
	detail := e.Payload
	if m, ok := e.Payload.(map[string]any); ok {
		if d, ok := m["detail"]; ok {
			detail = d
		} else if d, ok := m["error"]; ok {
			detail = d
		}
	}
	text, _ := json.Marshal(detail)
	return fmt.Sprintf("trigon: %d: %s", e.Status, text)
}

// Client calls a Trigon gateway.
type Client struct {
	BaseURL string
	// Headers are sent with every request: an Authorization bearer key, and
	// on a Modal deployment its Modal-Key and Modal-Secret.
	Headers map[string]string
	HTTP    *http.Client
}

// NewClient returns a client for the gateway at baseURL with a 30 s timeout.
func NewClient(baseURL string) *Client {
	return &Client{
		BaseURL: strings.TrimRight(baseURL, "/"),
		Headers: map[string]string{},
		HTTP:    &http.Client{Timeout: 30 * time.Second},
	}
}

// DecideOptions are the optional fields of a decision request.
type DecideOptions struct {
	Model   string
	Options map[string]any
}

// Decide answers a map of typed questions about one state, in a single pass.
// State is text, a JSON-shaped value, or a list of documents.
func (c *Client) Decide(
	ctx context.Context, state any, questions map[string]Question, opts *DecideOptions,
) (*Response, error) {
	body := map[string]any{"state": state, "questions": questions}
	if opts != nil {
		if opts.Model != "" {
			body["model"] = opts.Model
		}
		if len(opts.Options) > 0 {
			body["options"] = opts.Options
		}
	}
	var out Response
	if err := c.call(ctx, http.MethodPost, "/v1/decide", body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Model is one serving tier and the concrete build it runs.
type Model struct {
	Tier  string `json:"tier"`
	Model string `json:"model"`
}

// Models lists the serving tiers and the concrete build each one runs.
func (c *Client) Models(ctx context.Context) ([]Model, error) {
	var out struct {
		Data []Model `json:"data"`
	}
	if err := c.call(ctx, http.MethodGet, "/v1/models", nil, &out); err != nil {
		return nil, err
	}
	return out.Data, nil
}

// Healthz reports liveness, and whether this deployment is calibrated and trained.
func (c *Client) Healthz(ctx context.Context) (map[string]any, error) {
	var out map[string]any
	if err := c.call(ctx, http.MethodGet, "/healthz", nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) call(ctx context.Context, method, path string, body, out any) error {
	var reader io.Reader
	if body != nil {
		encoded, err := json.Marshal(body)
		if err != nil {
			return err
		}
		reader = bytes.NewReader(encoded)
	}
	req, err := http.NewRequestWithContext(ctx, method, c.BaseURL+path, reader)
	if err != nil {
		return err
	}
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	for k, v := range c.Headers {
		req.Header.Set(k, v)
	}
	httpClient := c.HTTP
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		var payload any
		if json.Unmarshal(data, &payload) != nil {
			payload = string(data)
		}
		return &Error{Status: resp.StatusCode, Payload: payload}
	}
	if len(data) == 0 {
		return nil
	}
	return json.Unmarshal(data, out)
}
