"""Typed client for the Trigon System One API.

Generated by ``scripts/generate_sdk.py`` from ``spec/openapi.json``.
Do not edit: regenerate instead, or ``tests/test_sdk.py`` fails.

Contract version 0.1.0.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from dataclasses import dataclass, fields
from typing import Any

CONTRACT_VERSION = "0.1.0"


class TrigonError(RuntimeError):
    """A non-2xx response. ``status`` and ``payload`` carry the detail."""

    def __init__(self, status: int, payload: Any) -> None:
        self.status = status
        self.payload = payload
        detail = payload
        if isinstance(payload, dict):
            detail = payload.get("detail") or payload.get("error") or payload
        super().__init__(f"{status}: {detail}")


@dataclass(frozen=True)
class Usage:
    """``Usage`` as the API returns it."""

    #: Schema tokens served from a cross-request KV prefix cache rather than
    #: recomputed. 0 means this request recomputed its schema block -- either
    #: the cache is off, or this was the first request carrying this schema.
    #: Read a 0 as 'not cached on this request', never as 'not cacheable': the
    #: layout makes the schema prefix cacheable and tests/test_independence.py
    #: asserts it.
    cached_schema_tokens: int = 0
    #: Total tokens prefilled. There is no decode half, so this is the whole
    #: cost.
    prefill_tokens: int = 0
    #: Readout slots, one or more per question.
    readout_tokens: int = 0
    #: Tokens the question schemas compiled to, across all questions.
    schema_tokens: int = 0
    #: Tokens the state compiled to.
    state_tokens: int = 0

    @classmethod
    def from_dict(cls, payload: dict) -> Usage:
        return cls(**{k: v for k, v in payload.items() if k in _FIELDS[cls]})


@dataclass(frozen=True)
class Timing:
    """``Timing`` as the API returns it."""

    #: Compiling the schema layout and its attention mask.
    compile_ms: float = 0.0
    #: The single forward pass. There is no decode.
    model_ms: float = 0.0
    #: Wall clock for the whole request.
    total_ms: float = 0.0

    @classmethod
    def from_dict(cls, payload: dict) -> Timing:
        return cls(**{k: v for k, v in payload.items() if k in _FIELDS[cls]})


@dataclass(frozen=True)
class ChoiceAnswer:
    """A distribution over exactly the options the request declared."""

    #: How concentrated the distribution is, scaled by log(option count) so a
    #: 2-option and a 77-option answer read comparably: 0 is uniform, 1 is
    #: certain. Derived from the calibrated distribution, and always from the
    #: full one.
    confidence: float
    #: Calibrated probability per option, in declared order. Sums to 1 unless
    #: `truncated`.
    probabilities: dict[str, float]
    #: The most probable option. Always one you declared.
    selected: str
    #: The coverage that prediction set guarantees.
    coverage_target: float | None = None
    #: Present when a conformal profile was applied: the options that survive
    #: at the profile's coverage target. A singleton set is the useful case; an
    #: empty one means abstain, not that no answer exists.
    prediction_set: list[str] | None = None
    #: How much of the distribution survived trimming.
    probability_mass: float | None = None
    #: The pre-calibration distribution, if you asked for it.
    raw_probabilities: dict[str, float] | None = None
    #: Present when the large-cardinality stage narrowed the option set: how
    #: many options you declared. Options the prefilter dropped come back at
    #: probability 0 rather than being omitted -- you declared them, so the
    #: answer mentions them.
    shortlisted_from: int | None = None
    #: True when `top_probabilities` trimmed the distribution. The
    #: probabilities returned are then the real ones, NOT renormalised, so they
    #: sum to less than 1; `probability_mass` says how much they cover.
    #: `selected` and `confidence` are computed over the full distribution
    #: either way.
    truncated: bool = False
    type: str = "choice"

    @classmethod
    def from_dict(cls, payload: dict) -> ChoiceAnswer:
        return cls(**{k: v for k, v in payload.items() if k in _FIELDS[cls]})


@dataclass(frozen=True)
class ScoreAnswer:
    """A distribution over the declared levels, plus its expectation."""

    #: Concentration of an ORDERED distribution, from its dispersion rather
    #: than its entropy -- mass on two adjacent levels is more confident than
    #: the same mass split across the ends, and entropy cannot see the
    #: difference.
    confidence: float
    #: Calibrated probability per level.
    probabilities: dict[str, float]
    #: The expectation of the distribution below, on your level values (or
    #: level indices when you declared none). Not a regression output: it
    #: cannot land outside the scale you declared.
    score: float
    #: The coverage that prediction set guarantees.
    coverage_target: float | None = None
    #: Levels surviving the conformal profile, if one was applied.
    prediction_set: list[str] | None = None
    #: How much of the distribution survived trimming.
    probability_mass: float | None = None
    #: The pre-calibration distribution, if you asked for it.
    raw_probabilities: dict[str, float] | None = None
    #: See ChoiceAnswer. `score` and `confidence` are always computed over the
    #: full distribution, never over what survived truncation.
    truncated: bool = False
    type: str = "score"

    @classmethod
    def from_dict(cls, payload: dict) -> ScoreAnswer:
        return cls(**{k: v for k, v in payload.items() if k in _FIELDS[cls]})


@dataclass(frozen=True)
class NoulAnswer:
    """No confidence field, by design: for a binary question the probability
    already carries everything a confidence statistic could summarise."""

    #: Calibrated probability that the judgement holds. There is no confidence
    #: field by design: for a binary question the probability already carries
    #: everything a confidence statistic could summarise, and 0.5 is the model
    #: saying it does not know.
    probability: float
    #: The pre-calibration probability, if you asked for it.
    raw_probability: float | None = None
    type: str = "noul"

    @classmethod
    def from_dict(cls, payload: dict) -> NoulAnswer:
        return cls(**{k: v for k, v in payload.items() if k in _FIELDS[cls]})


#: Discriminated on ``type``, exactly as the contract declares it: a
#: Choice answer is a distribution over the options you sent, a Score
#: adds an expectation, and a Noul has no confidence field by design.
_ANSWERS = {
    "choice": ChoiceAnswer,
    "score": ScoreAnswer,
    "noul": NoulAnswer,
}

_FIELDS = {
    cls: {f.name for f in fields(cls)}
    for cls in (Usage, Timing, ChoiceAnswer, ScoreAnswer, NoulAnswer)
}


def parse_answer(payload: dict) -> ChoiceAnswer | ScoreAnswer | NoulAnswer:
    """One answer, as the type it declares itself to be."""
    kind = payload.get("type")
    if kind not in _ANSWERS:
        raise TrigonError(0, f"unknown answer type {kind!r}")
    return _ANSWERS[kind].from_dict(payload)


@dataclass(frozen=True)
class Response:
    """One request's answers, plus what it cost."""

    id: str
    #: The concrete build that answered. Never an alias, and a model
    #: trained on nothing says so in this string.
    model: str
    answers: dict[str, ChoiceAnswer | ScoreAnswer | NoulAnswer]
    usage: Usage
    timing: Timing
    tier: str = "workhorse"

    @classmethod
    def from_dict(cls, payload: dict) -> Response:
        return cls(
            id=payload["id"],
            model=payload["model"],
            answers={qid: parse_answer(a) for qid, a in payload["answers"].items()},
            usage=Usage.from_dict(payload.get("usage", {})),
            timing=Timing.from_dict(payload.get("timing", {})),
            tier=payload.get("tier", "workhorse"),
        )


# -- question builders -------------------------------------------------
#
# The request side stays plain dicts: the gateway validates them and
# returns a 422 naming the offending field, which is a better error than
# one this client could invent. These are conveniences, not a schema.


def choice(instructions: str, options, **extra) -> dict:
    """A Choice: pick one of ``options``, which may be names or dicts."""
    return {
        "type": "choice",
        "instructions": instructions,
        "options": [o if isinstance(o, dict) else {"name": o} for o in options],
        **extra,
    }


def score(instructions: str, levels, **extra) -> dict:
    """A Score: a distribution over ordered ``levels``, low to high."""
    return {
        "type": "score",
        "instructions": instructions,
        "levels": [lv if isinstance(lv, dict) else {"name": lv} for lv in levels],
        **extra,
    }


def noul(instructions: str, **extra) -> dict:
    """A Noul: a yes/no judgement. No confidence field, by design."""
    return {"type": "noul", "instructions": instructions, **extra}


class TrigonClient:
    """A client for one deployment. Standard library only.

    >>> client = TrigonClient("http://localhost:8000")
    >>> response = client.systemone(
    ...     state="the card payment was declined at the till",
    ...     questions={"urgent": noul("Needs a human within the hour?")},
    ... )
    >>> response.answers["urgent"].probability  # doctest: +SKIP
    0.61
    """

    def __init__(
        self,
        base_url: str = "http://localhost:8000",
        *,
        timeout: float = 30.0,
        headers: dict[str, str] | None = None,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.headers = dict(headers or {})

    def systemone(
        self,
        state,
        questions: dict[str, dict],
        *,
        model: str | None = None,
        options: dict | None = None,
    ) -> Response:
        """The incumbent's request and response shapes, answered by this model

        ``state`` is text, a JSON-shaped mapping, or a list of documents.
        Every question is answered in the same forward pass, and none can
        influence another.
        """
        body: dict = {"state": state, "questions": questions}
        if model is not None:
            body["model"] = model
        if options:
            body["options"] = options
        return Response.from_dict(self._call("POST", "/compat/v1/systemone", body))

    def healthz(self) -> dict:
        """Liveness and calibration status"""
        return self._call("GET", "/healthz")

    def models(self) -> dict:
        """Serving tiers and their versions"""
        return self._call("GET", "/v1/models")

    def systemone(
        self,
        state,
        questions: dict[str, dict],
        *,
        model: str | None = None,
        options: dict | None = None,
    ) -> Response:
        """Answer a map of typed questions about one state

        ``state`` is text, a JSON-shaped mapping, or a list of documents.
        Every question is answered in the same forward pass, and none can
        influence another.
        """
        body: dict = {"state": state, "questions": questions}
        if model is not None:
            body["model"] = model
        if options:
            body["options"] = options
        return Response.from_dict(self._call("POST", "/v1/systemone", body))

    # -- transport -----------------------------------------------------

    def _call(self, method: str, path: str, body: dict | None = None) -> Any:
        data = json.dumps(body).encode() if body is not None else None
        headers = {"Accept": "application/json", **self.headers}
        if data is not None:
            headers["Content-Type"] = "application/json"
        request = urllib.request.Request(
            self.base_url + path, data=data, headers=headers, method=method
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                return json.loads(response.read() or b"null")
        except urllib.error.HTTPError as error:  # noqa: PERF203
            raw = error.read()
            try:
                payload = json.loads(raw)
            except ValueError:
                payload = raw.decode("utf-8", "replace")
            raise TrigonError(error.code, payload) from None


__all__ = [
    "CONTRACT_VERSION",
    "ChoiceAnswer",
    "NoulAnswer",
    "Response",
    "ScoreAnswer",
    "Timing",
    "TrigonClient",
    "TrigonError",
    "Usage",
    "choice",
    "noul",
    "parse_answer",
    "score",
]
