/**
 * Typed client for the Trigon System One API.
 *
 * Generated by scripts/generate_sdk.py from spec/openapi.json.
 * Do not edit: regenerate instead, or tests/test_sdk.py fails.
 *
 * Contract version 0.1.0.
 */

export const CONTRACT_VERSION = "0.1.0";

export interface Usage {
  /**
   * Schema tokens served from a cross-request KV prefix cache rather than
   * recomputed. 0 means this request recomputed its schema block -- either
   * the cache is off, or this was the first request carrying this schema.
   * Read a 0 as 'not cached on this request', never as 'not cacheable':
   * the layout makes the schema prefix cacheable and
   * tests/test_independence.py asserts it.
   */
  cached_schema_tokens?: number;
  /**
   * Total tokens prefilled. There is no decode half, so this is the whole
   * cost.
   */
  prefill_tokens?: number;
  /**
   * Readout slots, one or more per question.
   */
  readout_tokens?: number;
  /**
   * Tokens the question schemas compiled to, across all questions.
   */
  schema_tokens?: number;
  /**
   * Tokens the state compiled to.
   */
  state_tokens?: number;
}

export interface Timing {
  /**
   * Compiling the schema layout and its attention mask.
   */
  compile_ms?: number;
  /**
   * The single forward pass. There is no decode.
   */
  model_ms?: number;
  /**
   * Wall clock for the whole request.
   */
  total_ms?: number;
}

/**
 * One span of the state that drove an answer.
 */
export interface EvidenceSpan {
  /**
   * One past the last character, so `state[start:end]` is the span.
   */
  end: number;
  /**
   * How strongly this span drove the answer. Under `span_head` it is the
   * head's probability that the span is part of a human rationale, fitted
   * with a proper scoring rule and never calibrated or gated; under
   * `gradient_x_input` it is relative within this answer, 1 being its
   * strongest token, and is not a probability at all.
   */
  score: number;
  /**
   * First character of the span in the state string.
   */
  start: number;
  /**
   * `state[start:end]`, so a caller need not slice it.
   */
  text: string;
}

/**
 * A distribution over exactly the options the request declared.
 */
export interface ChoiceAnswer {
  /**
   * How concentrated the distribution is, scaled by log(option count) so a
   * 2-option and a 77-option answer read comparably: 0 is uniform, 1 is
   * certain. Derived from the calibrated distribution, and always from the
   * full one.
   */
  confidence: number;
  /**
   * The coverage that prediction set guarantees.
   */
  coverage_target?: number | null;
  /**
   * Present when `include_evidence` was asked for: the spans of the state
   * that drove this answer, in order of position. Empty means nothing
   * cleared the threshold, which is an answer, not an error.
   */
  evidence?: EvidenceSpan[] | null;
  /**
   * How `evidence` was produced. `span_head`: a head trained on human
   * rationales. `gradient_x_input`: attribution of the selected label to
   * each state token, from a model never shown a rationale -- a statement
   * about the model, not a prediction of what a person would highlight.
   * `lexical_overlap`: the lexical floor's word matches. `unavailable`:
   * this backend cannot attribute, and `evidence` is empty for that reason
   * rather than because nothing mattered.
   */
  evidence_method?: "span_head" | "gradient_x_input" | "lexical_overlap" | "unavailable" | null;
  /**
   * Present when a conformal profile was applied: the options that survive
   * at the profile's coverage target. A singleton set is the useful case;
   * an empty one means abstain, not that no answer exists.
   */
  prediction_set?: string[] | null;
  /**
   * Calibrated probability per option, in declared order. Sums to 1 unless
   * `truncated`.
   */
  probabilities: Record<string, number>;
  /**
   * How much of the distribution survived trimming.
   */
  probability_mass?: number | null;
  /**
   * The pre-calibration distribution, if you asked for it.
   */
  raw_probabilities?: Record<string, number> | null;
  /**
   * The most probable option. Always one you declared.
   */
  selected: string;
  /**
   * Present when the large-cardinality stage narrowed the option set: how
   * many options you declared. Options the prefilter dropped come back at
   * probability 0 rather than being omitted -- you declared them, so the
   * answer mentions them.
   */
  shortlisted_from?: number | null;
  /**
   * True when `top_probabilities` trimmed the distribution. The
   * probabilities returned are then the real ones, NOT renormalised, so
   * they sum to less than 1; `probability_mass` says how much they cover.
   * `selected` and `confidence` are computed over the full distribution
   * either way.
   */
  truncated?: boolean;
  type?: "choice";
}

/**
 * A distribution over the declared levels, plus its expectation.
 */
export interface ScoreAnswer {
  /**
   * Concentration of an ORDERED distribution, from its dispersion rather
   * than its entropy -- mass on two adjacent levels is more confident than
   * the same mass split across the ends, and entropy cannot see the
   * difference.
   */
  confidence: number;
  /**
   * The coverage that prediction set guarantees.
   */
  coverage_target?: number | null;
  /**
   * Present when `include_evidence` was asked for: the spans of the state
   * that drove this answer, in order of position. Empty means nothing
   * cleared the threshold, which is an answer, not an error.
   */
  evidence?: EvidenceSpan[] | null;
  /**
   * How `evidence` was produced. `span_head`: a head trained on human
   * rationales. `gradient_x_input`: attribution of the selected label to
   * each state token, from a model never shown a rationale -- a statement
   * about the model, not a prediction of what a person would highlight.
   * `lexical_overlap`: the lexical floor's word matches. `unavailable`:
   * this backend cannot attribute, and `evidence` is empty for that reason
   * rather than because nothing mattered.
   */
  evidence_method?: "span_head" | "gradient_x_input" | "lexical_overlap" | "unavailable" | null;
  /**
   * Levels surviving the conformal profile, if one was applied.
   */
  prediction_set?: string[] | null;
  /**
   * Calibrated probability per level.
   */
  probabilities: Record<string, number>;
  /**
   * How much of the distribution survived trimming.
   */
  probability_mass?: number | null;
  /**
   * The pre-calibration distribution, if you asked for it.
   */
  raw_probabilities?: Record<string, number> | null;
  /**
   * The expectation of the distribution below, on your level values (or
   * level indices when you declared none). Not a regression output: it
   * cannot land outside the scale you declared.
   */
  score: number;
  /**
   * See ChoiceAnswer. `score` and `confidence` are always computed over
   * the full distribution, never over what survived truncation.
   */
  truncated?: boolean;
  type?: "score";
}

/**
 * No confidence field, by design: for a binary question the probability
 * already carries everything a confidence statistic could summarise.
 */
export interface NoulAnswer {
  /**
   * Present when `include_evidence` was asked for: the spans of the state
   * that drove this answer, in order of position. Empty means nothing
   * cleared the threshold, which is an answer, not an error.
   */
  evidence?: EvidenceSpan[] | null;
  /**
   * How `evidence` was produced. `span_head`: a head trained on human
   * rationales. `gradient_x_input`: attribution of the selected label to
   * each state token, from a model never shown a rationale -- a statement
   * about the model, not a prediction of what a person would highlight.
   * `lexical_overlap`: the lexical floor's word matches. `unavailable`:
   * this backend cannot attribute, and `evidence` is empty for that reason
   * rather than because nothing mattered.
   */
  evidence_method?: "span_head" | "gradient_x_input" | "lexical_overlap" | "unavailable" | null;
  /**
   * Calibrated probability that the judgement holds. There is no
   * confidence field by design: for a binary question the probability
   * already carries everything a confidence statistic could summarise, and
   * 0.5 is the model saying it does not know.
   */
  probability: number;
  /**
   * The pre-calibration probability, if you asked for it.
   */
  raw_probability?: number | null;
  type?: "noul";
}

/** Discriminated on `type`, exactly as the contract declares it. */
export type Answer = ChoiceAnswer | ScoreAnswer | NoulAnswer;

export interface Response {
  id: string;
  /** The concrete build that answered. Never an alias. */
  model: string;
  answers: Record<string, Answer>;
  usage: Usage;
  timing: Timing;
  tier: string;
}

/** State is text, a JSON-shaped object, or a list of documents. */
export type State = string | Record<string, unknown> | unknown[];

export type Question = Record<string, unknown>;

/** A non-2xx response. `status` and `payload` carry the detail. */
export class TrigonError extends Error {
  readonly status: number;
  readonly payload: unknown;

  constructor(status: number, payload: unknown) {
    const detail =
      payload && typeof payload === "object"
        ? ((payload as Record<string, unknown>).detail ??
           (payload as Record<string, unknown>).error ??
           payload)
        : payload;
    super(`${status}: ${JSON.stringify(detail)}`);
    this.name = "TrigonError";
    this.status = status;
    this.payload = payload;
  }
}

// -- question builders -------------------------------------------------
//
// The request side stays plain objects: the gateway validates them and
// returns a 422 naming the offending field, which is a better error than
// one this client could invent.

export function choice(
  instructions: string,
  options: (string | Record<string, unknown>)[],
  extra: Record<string, unknown> = {},
): Question {
  return {
    type: "choice",
    instructions,
    options: options.map((o) => (typeof o === "string" ? { name: o } : o)),
    ...extra,
  };
}

export function score(
  instructions: string,
  levels: (string | Record<string, unknown>)[],
  extra: Record<string, unknown> = {},
): Question {
  return {
    type: "score",
    instructions,
    levels: levels.map((l) => (typeof l === "string" ? { name: l } : l)),
    ...extra,
  };
}

/** A yes/no judgement. No confidence field, by design. */
export function noul(
  instructions: string,
  extra: Record<string, unknown> = {},
): Question {
  return { type: "noul", instructions, ...extra };
}

export interface ClientOptions {
  baseUrl?: string;
  timeoutMs?: number;
  headers?: Record<string, string>;
  fetch?: typeof globalThis.fetch;
}

export class TrigonClient {
  private readonly baseUrl: string;
  private readonly timeoutMs: number;
  private readonly headers: Record<string, string>;
  private readonly fetchImpl: typeof globalThis.fetch;

  constructor(options: ClientOptions | string = {}) {
    const opts = typeof options === "string" ? { baseUrl: options } : options;
    this.baseUrl = (opts.baseUrl ?? "http://localhost:8000").replace(/\/+$/, "");
    this.timeoutMs = opts.timeoutMs ?? 30_000;
    this.headers = { ...(opts.headers ?? {}) };
    this.fetchImpl = opts.fetch ?? globalThis.fetch;
  }

  /** Answer a map of typed questions about one state, in a single pass. */
  async systemone(
    state: State,
    questions: Record<string, Question>,
    options: { model?: string; options?: Record<string, unknown> } = {},
  ): Promise<Response> {
    const body: Record<string, unknown> = { state, questions };
    if (options.model !== undefined) body.model = options.model;
    if (options.options) body.options = options.options;
    return (await this.call("POST", "/v1/systemone", body)) as Response;
  }

  /** Serving tiers and the concrete build each one runs. */
  async models(): Promise<{ data: { tier: string; model: string }[] }> {
    return (await this.call("GET", "/v1/models")) as {
      data: { tier: string; model: string }[];
    };
  }

  /** Liveness, plus whether this deployment is calibrated and trained. */
  async healthz(): Promise<Record<string, unknown>> {
    return (await this.call("GET", "/healthz")) as Record<string, unknown>;
  }

  private async call(
    method: string,
    path: string,
    body?: Record<string, unknown>,
  ): Promise<unknown> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.timeoutMs);
    try {
      const response = await this.fetchImpl(this.baseUrl + path, {
        method,
        signal: controller.signal,
        headers: {
          Accept: "application/json",
          ...(body ? { "Content-Type": "application/json" } : {}),
          ...this.headers,
        },
        // Spread rather than `body: undefined`: under
        // exactOptionalPropertyTypes an explicit undefined is not the
        // same as an absent key, and RequestInit does not accept it.
        ...(body ? { body: JSON.stringify(body) } : {}),
      });
      const text = await response.text();
      let payload: unknown = null;
      if (text) {
        try {
          payload = JSON.parse(text);
        } catch {
          payload = text;
        }
      }
      if (!response.ok) throw new TrigonError(response.status, payload);
      return payload;
    } finally {
      clearTimeout(timer);
    }
  }
}
