#!/usr/bin/env python
"""Generate the Python SDK from spec/openapi.json.

    python scripts/generate_sdk.py            # write sdk/python/trigon_client/_generated.py
    python scripts/generate_sdk.py --check    # fail if the checked-in file is stale

The spec is the contract and it is checked in precisely so things can be built
from it; this is the first thing that is. ``tests/test_sdk.py`` runs this with
``--check``, so a change to ``trigon.types`` that is exported to the spec and
not regenerated here fails CI in the same commit — the same drift discipline
``tests/test_openapi_drift.py`` applies to the spec itself.

**Why a generator rather than a hand-written client.** A hand-written client
is a second definition of the contract, and two definitions drift. This one
reads the schemas and emits dataclasses and parsers for whatever it finds, so a
field added to an answer appears in the SDK without anyone remembering to add
it.

**Why no dependencies.** The generated client imports only the standard
library. An SDK is the first thing a prospective user installs, and one that
drags in an HTTP stack to call three endpoints is a worse first impression than
forty lines of ``urllib``.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "spec" / "openapi.json"
OUT = ROOT / "sdk" / "python" / "trigon_client" / "_generated.py"
OUT_TS = ROOT / "sdk" / "typescript" / "src" / "generated.ts"

#: Schemas the client models as dataclasses. Request-side schemas are left as
#: plain dicts on purpose: the gateway validates them and returns a 422 naming
#: the field, which is a better error than one this client could invent.
ANSWER_SCHEMAS = ("ChoiceAnswer", "ScoreAnswer", "NoulAnswer")
VALUE_SCHEMAS = ("Usage", "Timing")

_PY_TYPES = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "object": "dict",
    "array": "list",
}


def _annotation(schema: dict) -> tuple[str, bool]:
    """A Python annotation for one property, and whether it is optional."""
    if "anyOf" in schema:
        parts = [s for s in schema["anyOf"] if s.get("type") != "null"]
        optional = len(parts) != len(schema["anyOf"])
        inner = _annotation(parts[0])[0] if parts else "object"
        return (f"{inner} | None" if optional else inner), optional
    kind = schema.get("type")
    if kind == "array":
        return f"list[{_annotation(schema.get('items', {}))[0]}]", False
    if kind == "object":
        values = schema.get("additionalProperties")
        if isinstance(values, dict):
            return f"dict[str, {_annotation(values)[0]}]", False
        return "dict", False
    if "const" in schema:
        return "str", False
    return _PY_TYPES.get(kind, "object"), False


def _fields(schema: dict) -> list[tuple[str, str, str | None]]:
    """(name, annotation, default) for each property, required ones first."""
    required = set(schema.get("required", ()))
    out = []
    for name, prop in schema.get("properties", {}).items():
        annotation, optional = _annotation(prop)
        if name in required and not optional:
            default = None
        elif "default" in prop:
            default = repr(prop["default"])
        else:
            default = "None"
        out.append((name, annotation, default))
    return sorted(out, key=lambda f: f[2] is not None)


def _dataclass(name: str, schema: dict) -> str:
    lines = ["@dataclass(frozen=True)", f"class {name}:"]
    doc = schema.get("description") or f"``{name}`` as the API returns it."
    lines.append(f'    """{doc}"""')
    lines.append("")
    for field_name, annotation, default in _fields(schema):
        prop = schema["properties"][field_name]
        if prop.get("description"):
            for line in _wrap(prop["description"], 72):
                lines.append(f"    #: {line}")
        suffix = f" = {default}" if default is not None else ""
        lines.append(f"    {field_name}: {annotation}{suffix}")
    lines.append("")
    lines.append("    @classmethod")
    lines.append(f"    def from_dict(cls, payload: dict) -> {name}:")
    lines.append("        return cls(**{k: v for k, v in payload.items() if k in _FIELDS[cls]})")
    return "\n".join(lines)


def _wrap(text: str, width: int) -> list[str]:
    import textwrap

    return textwrap.wrap(" ".join(text.split()), width) or [""]


def render(spec: dict) -> str:
    schemas = spec["components"]["schemas"]
    version = spec.get("info", {}).get("version", "0")

    parts = [
        '"""Typed client for the Trigon System One API.',
        "",
        "Generated by ``scripts/generate_sdk.py`` from ``spec/openapi.json``.",
        "Do not edit: regenerate instead, or ``tests/test_sdk.py`` fails.",
        "",
        f"Contract version {version}.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "import urllib.error",
        "import urllib.request",
        "from dataclasses import dataclass, fields",
        "from typing import Any",
        "",
        f'CONTRACT_VERSION = "{version}"',
        "",
        "",
        "class TrigonError(RuntimeError):",
        '    """A non-2xx response. ``status`` and ``payload`` carry the detail."""',
        "",
        "    def __init__(self, status: int, payload: Any) -> None:",
        "        self.status = status",
        "        self.payload = payload",
        "        detail = payload",
        "        if isinstance(payload, dict):",
        '            detail = payload.get("detail") or payload.get("error") or payload',
        '        super().__init__(f"{status}: {detail}")',
        "",
    ]

    for name in VALUE_SCHEMAS + ANSWER_SCHEMAS:
        parts += ["", _dataclass(name, schemas[name]), ""]

    parts += [
        "",
        "#: Discriminated on ``type``, exactly as the contract declares it: a",
        "#: Choice answer is a distribution over the options you sent, a Score",
        "#: adds an expectation, and a Noul has no confidence field by design.",
        "_ANSWERS = {",
        '    "choice": ChoiceAnswer,',
        '    "score": ScoreAnswer,',
        '    "noul": NoulAnswer,',
        "}",
        "",
        "_FIELDS = {",
        "    cls: {f.name for f in fields(cls)}",
        "    for cls in (Usage, Timing, ChoiceAnswer, ScoreAnswer, NoulAnswer)",
        "}",
        "",
        "",
        "def parse_answer(payload: dict) -> ChoiceAnswer | ScoreAnswer | NoulAnswer:",
        '    """One answer, as the type it declares itself to be."""',
        '    kind = payload.get("type")',
        "    if kind not in _ANSWERS:",
        '        raise TrigonError(0, f"unknown answer type {kind!r}")',
        "    return _ANSWERS[kind].from_dict(payload)",
        "",
        "",
        "@dataclass(frozen=True)",
        "class Response:",
        '    """One request\'s answers, plus what it cost."""',
        "",
        "    id: str",
        "    #: The concrete build that answered. Never an alias, and a model",
        "    #: trained on nothing says so in this string.",
        "    model: str",
        "    answers: dict[str, ChoiceAnswer | ScoreAnswer | NoulAnswer]",
        "    usage: Usage",
        "    timing: Timing",
        '    tier: str = "workhorse"',
        "",
        "    @classmethod",
        "    def from_dict(cls, payload: dict) -> Response:",
        "        return cls(",
        '            id=payload["id"],',
        '            model=payload["model"],',
        "            answers={",
        '                qid: parse_answer(a) for qid, a in payload["answers"].items()',
        "            },",
        '            usage=Usage.from_dict(payload.get("usage", {})),',
        '            timing=Timing.from_dict(payload.get("timing", {})),',
        '            tier=payload.get("tier", "workhorse"),',
        "        )",
        "",
        "",
        "# -- question builders -------------------------------------------------",
        "#",
        "# The request side stays plain dicts: the gateway validates them and",
        "# returns a 422 naming the offending field, which is a better error than",
        "# one this client could invent. These are conveniences, not a schema.",
        "",
        "",
        "def choice(instructions: str, options, **extra) -> dict:",
        '    """A Choice: pick one of ``options``, which may be names or dicts."""',
        "    return {",
        '        "type": "choice",',
        '        "instructions": instructions,',
        '        "options": [',
        '            o if isinstance(o, dict) else {"name": o} for o in options',
        "        ],",
        "        **extra,",
        "    }",
        "",
        "",
        "def score(instructions: str, levels, **extra) -> dict:",
        '    """A Score: a distribution over ordered ``levels``, low to high."""',
        "    return {",
        '        "type": "score",',
        '        "instructions": instructions,',
        '        "levels": [lv if isinstance(lv, dict) else {"name": lv} for lv in levels],',
        "        **extra,",
        "    }",
        "",
        "",
        "def noul(instructions: str, **extra) -> dict:",
        '    """A Noul: a yes/no judgement. No confidence field, by design."""',
        '    return {"type": "noul", "instructions": instructions, **extra}',
        "",
        "",
        "class TrigonClient:",
        '    """A client for one deployment. Standard library only.',
        "",
        '    >>> client = TrigonClient("http://localhost:8000")',
        "    >>> response = client.systemone(",
        '    ...     state="the card payment was declined at the till",',
        '    ...     questions={"urgent": noul("Needs a human within the hour?")},',
        "    ... )",
        '    >>> response.answers["urgent"].probability  # doctest: +SKIP',
        "    0.61",
        '    """',
        "",
        "    def __init__(",
        "        self,",
        '        base_url: str = "http://localhost:8000",',
        "        *,",
        "        timeout: float = 30.0,",
        "        headers: dict[str, str] | None = None,",
        "    ) -> None:",
        '        self.base_url = base_url.rstrip("/")',
        "        self.timeout = timeout",
        "        self.headers = dict(headers or {})",
        "",
    ]

    for path, operations in spec["paths"].items():
        for method, operation in operations.items():
            name = _method_name(path)
            summary = operation.get("summary") or operation.get("description") or path
            parts += _client_method(name, method, path, summary, operation)

    parts += [
        "    # -- transport -----------------------------------------------------",
        "",
        "    def _call(self, method: str, path: str, body: dict | None = None) -> Any:",
        "        data = json.dumps(body).encode() if body is not None else None",
        '        headers = {"Accept": "application/json", **self.headers}',
        "        if data is not None:",
        '            headers["Content-Type"] = "application/json"',
        "        request = urllib.request.Request(",
        "            self.base_url + path, data=data, headers=headers, method=method",
        "        )",
        "        try:",
        "            with urllib.request.urlopen(request, timeout=self.timeout) as response:",
        '                return json.loads(response.read() or b"null")',
        "        except urllib.error.HTTPError as error:  # noqa: PERF203",
        "            raw = error.read()",
        "            try:",
        "                payload = json.loads(raw)",
        "            except ValueError:",
        '                payload = raw.decode("utf-8", "replace")',
        "            raise TrigonError(error.code, payload) from None",
        "",
        "",
        "__all__ = [",
        '    "CONTRACT_VERSION",',
        '    "ChoiceAnswer",',
        '    "NoulAnswer",',
        '    "Response",',
        '    "ScoreAnswer",',
        '    "Timing",',
        '    "TrigonClient",',
        '    "TrigonError",',
        '    "Usage",',
        '    "choice",',
        '    "noul",',
        '    "parse_answer",',
        '    "score",',
        "]",
    ]
    return "\n".join(parts) + "\n"


# -- TypeScript ---------------------------------------------------------------

_TS_TYPES = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "object": "Record<string, unknown>",
}


def _ts_annotation(schema: dict) -> tuple[str, bool]:
    """A TypeScript type for one property, and whether it is nullable."""
    if "anyOf" in schema:
        parts = [s for s in schema["anyOf"] if s.get("type") != "null"]
        nullable = len(parts) != len(schema["anyOf"])
        inner = _ts_annotation(parts[0])[0] if parts else "unknown"
        return (f"{inner} | null" if nullable else inner), nullable
    kind = schema.get("type")
    if kind == "array":
        return f"{_ts_annotation(schema.get('items', {}))[0]}[]", False
    if kind == "object":
        values = schema.get("additionalProperties")
        if isinstance(values, dict):
            return f"Record<string, {_ts_annotation(values)[0]}>", False
        return "Record<string, unknown>", False
    if "const" in schema:
        return f'"{schema["const"]}"', False
    return _TS_TYPES.get(kind, "unknown"), False


def _ts_interface(name: str, schema: dict) -> list[str]:
    lines = []
    if schema.get("description"):
        lines.append("/**")
        lines += [f" * {line}" for line in _wrap(schema["description"], 72)]
        lines.append(" */")
    lines.append(f"export interface {name} {{")
    required = set(schema.get("required", ()))
    for field, prop in schema.get("properties", {}).items():
        annotation, nullable = _ts_annotation(prop)
        if prop.get("description"):
            lines.append("  /**")
            lines += [f"   * {line}" for line in _wrap(prop["description"], 70)]
            lines.append("   */")
        optional = "" if field in required and not nullable else "?"
        lines.append(f"  {field}{optional}: {annotation};")
    lines.append("}")
    lines.append("")
    return lines


def render_typescript(spec: dict) -> str:
    schemas = spec["components"]["schemas"]
    version = spec.get("info", {}).get("version", "0")
    out = [
        "/**",
        " * Typed client for the Trigon System One API.",
        " *",
        " * Generated by scripts/generate_sdk.py from spec/openapi.json.",
        " * Do not edit: regenerate instead, or tests/test_sdk.py fails.",
        " *",
        f" * Contract version {version}.",
        " */",
        "",
        f'export const CONTRACT_VERSION = "{version}";',
        "",
    ]
    for name in VALUE_SCHEMAS + ANSWER_SCHEMAS:
        out += _ts_interface(name, schemas[name])

    out += [
        "/** Discriminated on `type`, exactly as the contract declares it. */",
        "export type Answer = ChoiceAnswer | ScoreAnswer | NoulAnswer;",
        "",
        "export interface Response {",
        "  id: string;",
        "  /** The concrete build that answered. Never an alias. */",
        "  model: string;",
        "  answers: Record<string, Answer>;",
        "  usage: Usage;",
        "  timing: Timing;",
        "  tier: string;",
        "}",
        "",
        "/** State is text, a JSON-shaped object, or a list of documents. */",
        "export type State = string | Record<string, unknown> | unknown[];",
        "",
        "export type Question = Record<string, unknown>;",
        "",
        "/** A non-2xx response. `status` and `payload` carry the detail. */",
        "export class TrigonError extends Error {",
        "  readonly status: number;",
        "  readonly payload: unknown;",
        "",
        "  constructor(status: number, payload: unknown) {",
        "    const detail =",
        '      payload && typeof payload === "object"',
        "        ? ((payload as Record<string, unknown>).detail ??",
        "           (payload as Record<string, unknown>).error ??",
        "           payload)",
        "        : payload;",
        "    super(`${status}: ${JSON.stringify(detail)}`);",
        '    this.name = "TrigonError";',
        "    this.status = status;",
        "    this.payload = payload;",
        "  }",
        "}",
        "",
        "// -- question builders -------------------------------------------------",
        "//",
        "// The request side stays plain objects: the gateway validates them and",
        "// returns a 422 naming the offending field, which is a better error than",
        "// one this client could invent.",
        "",
        "export function choice(",
        "  instructions: string,",
        "  options: (string | Record<string, unknown>)[],",
        "  extra: Record<string, unknown> = {},",
        "): Question {",
        "  return {",
        '    type: "choice",',
        "    instructions,",
        '    options: options.map((o) => (typeof o === "string" ? { name: o } : o)),',
        "    ...extra,",
        "  };",
        "}",
        "",
        "export function score(",
        "  instructions: string,",
        "  levels: (string | Record<string, unknown>)[],",
        "  extra: Record<string, unknown> = {},",
        "): Question {",
        "  return {",
        '    type: "score",',
        "    instructions,",
        '    levels: levels.map((l) => (typeof l === "string" ? { name: l } : l)),',
        "    ...extra,",
        "  };",
        "}",
        "",
        "/** A yes/no judgement. No confidence field, by design. */",
        "export function noul(",
        "  instructions: string,",
        "  extra: Record<string, unknown> = {},",
        "): Question {",
        '  return { type: "noul", instructions, ...extra };',
        "}",
        "",
        "export interface ClientOptions {",
        "  baseUrl?: string;",
        "  timeoutMs?: number;",
        "  headers?: Record<string, string>;",
        "  fetch?: typeof globalThis.fetch;",
        "}",
        "",
        "export class TrigonClient {",
        "  private readonly baseUrl: string;",
        "  private readonly timeoutMs: number;",
        "  private readonly headers: Record<string, string>;",
        "  private readonly fetchImpl: typeof globalThis.fetch;",
        "",
        "  constructor(options: ClientOptions | string = {}) {",
        '    const opts = typeof options === "string" ? { baseUrl: options } : options;',
        '    this.baseUrl = (opts.baseUrl ?? "http://localhost:8000").replace(/\/+$/, "");',
        "    this.timeoutMs = opts.timeoutMs ?? 30_000;",
        "    this.headers = { ...(opts.headers ?? {}) };",
        "    this.fetchImpl = opts.fetch ?? globalThis.fetch;",
        "  }",
        "",
        "  /** Answer a map of typed questions about one state, in a single pass. */",
        "  async systemone(",
        "    state: State,",
        "    questions: Record<string, Question>,",
        "    options: { model?: string; options?: Record<string, unknown> } = {},",
        "  ): Promise<Response> {",
        "    const body: Record<string, unknown> = { state, questions };",
        "    if (options.model !== undefined) body.model = options.model;",
        "    if (options.options) body.options = options.options;",
        '    return (await this.call("POST", "/v1/systemone", body)) as Response;',
        "  }",
        "",
        "  /** Serving tiers and the concrete build each one runs. */",
        "  async models(): Promise<{ data: { tier: string; model: string }[] }> {",
        '    return (await this.call("GET", "/v1/models")) as {',
        "      data: { tier: string; model: string }[];",
        "    };",
        "  }",
        "",
        "  /** Liveness, plus whether this deployment is calibrated and trained. */",
        "  async healthz(): Promise<Record<string, unknown>> {",
        '    return (await this.call("GET", "/healthz")) as Record<string, unknown>;',
        "  }",
        "",
        "  private async call(",
        "    method: string,",
        "    path: string,",
        "    body?: Record<string, unknown>,",
        "  ): Promise<unknown> {",
        "    const controller = new AbortController();",
        "    const timer = setTimeout(() => controller.abort(), this.timeoutMs);",
        "    try {",
        "      const response = await this.fetchImpl(this.baseUrl + path, {",
        "        method,",
        "        signal: controller.signal,",
        "        headers: {",
        '          Accept: "application/json",',
        '          ...(body ? { "Content-Type": "application/json" } : {}),',
        "          ...this.headers,",
        "        },",
        "        // Spread rather than `body: undefined`: under",
        "        // exactOptionalPropertyTypes an explicit undefined is not the",
        "        // same as an absent key, and RequestInit does not accept it.",
        "        ...(body ? { body: JSON.stringify(body) } : {}),",
        "      });",
        "      const text = await response.text();",
        "      let payload: unknown = null;",
        "      if (text) {",
        "        try {",
        "          payload = JSON.parse(text);",
        "        } catch {",
        "          payload = text;",
        "        }",
        "      }",
        "      if (!response.ok) throw new TrigonError(response.status, payload);",
        "      return payload;",
        "    } finally {",
        "      clearTimeout(timer);",
        "    }",
        "  }",
        "}",
        "",
    ]
    return "\n".join(out)


def _method_name(path: str) -> str:
    stem = path.strip("/").replace("/", "_").replace("-", "_")
    if stem.startswith("v1_"):
        stem = stem[3:]
    return stem


def _client_method(name: str, method: str, path: str, summary: str, operation: dict) -> list[str]:
    takes_body = "requestBody" in operation
    if takes_body:
        return [
            "    def systemone(",
            "        self,",
            "        state,",
            "        questions: dict[str, dict],",
            "        *,",
            "        model: str | None = None,",
            "        options: dict | None = None,",
            "    ) -> Response:",
            f'        """{summary}',
            "",
            "        ``state`` is text, a JSON-shaped mapping, or a list of documents.",
            "        Every question is answered in the same forward pass, and none can",
            "        influence another.",
            '        """',
            '        body: dict = {"state": state, "questions": questions}',
            "        if model is not None:",
            '            body["model"] = model',
            "        if options:",
            '            body["options"] = options',
            f'        return Response.from_dict(self._call("{method.upper()}", "{path}", body))',
            "",
        ]
    return [
        f"    def {name}(self) -> dict:",
        f'        """{summary}"""',
        f'        return self._call("{method.upper()}", "{path}")',
        "",
    ]


def _format(source: str) -> str:
    """Run the emitted source through ruff, so the drift check is stable.

    Generated code still has to read like the rest of the repository, and
    hand-tuning every emitted string literal to match a formatter is a losing
    game. Ruff is a dev dependency and this is a dev tool; if it is missing the
    source is still valid Python, just not canonically spaced.
    """
    import shutil
    import subprocess

    ruff = shutil.which("ruff") or str(ROOT / ".venv" / "bin" / "ruff")
    if not pathlib.Path(ruff).exists():
        return source
    for args in (["check", "--fix", "--quiet"], ["format", "--quiet"]):
        result = subprocess.run(
            [ruff, *args, "--stdin-filename", str(OUT), "-"],
            input=source,
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0 and result.stdout:
            source = result.stdout
    return source


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    parser.add_argument("--out", default=str(OUT))
    parser.add_argument("--out-ts", default=str(OUT_TS))
    args = parser.parse_args()

    spec = json.loads(SPEC.read_text())
    outputs = [
        (pathlib.Path(args.out), _format(render(spec))),
        (pathlib.Path(args.out_ts), render_typescript(spec)),
    ]

    if args.check:
        stale = [t for t, want in outputs if (t.read_text() if t.exists() else "") != want]
        if stale:
            for target in stale:
                print(f"{target} is stale — run scripts/generate_sdk.py", file=sys.stderr)
            return 1
        for target, _ in outputs:
            print(f"{target} is current", file=sys.stderr)
        return 0

    for target, rendered in outputs:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered)
        print(f"wrote {target}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
